#theme = "catppuccin_mocha"
theme = "root-loops"

[editor]
line-number = "relative"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-o" = ["yank_to_clipboard", ":sh aichat \"explain this code\""]
