[language-server]
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

# Leptos
procMacro = {ignored = { leptos_macro = [
  # Optional:
  # "component",
  "server"
]}}

[language-server.rust-analyzer.config.cargo]
allFeatures = true

[language-server.rust-analyzer.config.files]
watcher = "server"

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "261b20226c04ef601adbdf185a800512a5f66291" }

# --- Language servers ---

[language-server.javascript-typescript-langserver]
command = "javascript-typescript-stdio"

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

# --- JavaScript / TypeScript ---

[[language]]
name = "javascript"
language-servers = [
  "javascript-typescript-langserver"
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "javascript-typescript-langserver"
]
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "javascript-typescript-langserver",
  "emmet-ls"
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "javascript-typescript-langserver",
  "emmet-ls"
]
auto-format = true

# --- HTML ---

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "emmet-ls"
]
auto-format = true

# Optional: CSS & Tailwind

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-language-server"
]
auto-format = true
